### ISSUE TITLE
Collapsed Row Drag Glitch

### ISSUE THREAD

**Issue by macisbetter** [mcguffin/acf-repeater-collapser#1]
If you drag a box while moving it slightly to the right, as if you were going to nest it, the arrow and number expand.  

https://www.evernote.com/l/APelSi3K-pNLLbOfzEtHMcsCOnW2ChcQhMk

Great Plug in, thank you very much!!!

**Comment by michaelgrime** [comment]
Since I updated to ACF Pro to 5.3.1 collapse functionality no longer works: I click on collapse arrow and nothing happens.

See this [demo on YouTube](https://youtu.be/FU7GRSBX2YE).

Best UI of the ACF collapse plugins, hope you get a chance to fix it :-)

**Comment by mcguffin** [comment]
@macisbetter As far as I can see the table layout is getting messed up when you either drag the first item or when you drag a row to the topmost position. I couldn't figure out why …

@michaelgrime issue fixed in latest commit.
